services:
    nodehub:
        image: ghcr.io/evilCYH/nodehub:latest
        container_name: nodehub
        restart: always
        ports:
            - '8080:8080'
        volumes:
            - './nodehub:/app/data'

